# set default underlying shell
set -g default-command "/bin/zsh"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# move pane to/from window
bind-key j command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:"  "join-pane -t '%%'"

# switch panes using Alt-arrow without prefix
bind-key -T prefix Left select-pane -L
bind-key -T prefix Right select-pane -R
bind-key -T prefix Up select-pane -U
bind-key -T prefix Down select-pane -D

# set resizing through keys
bind-key -r -T prefix       M-Up              resize-pane -U 5
bind-key -r -T prefix       M-Down            resize-pane -D 5
bind-key -r -T prefix       M-Left            resize-pane -L 5
bind-key -r -T prefix       M-Right           resize-pane -R 5
bind-key -r -T prefix       C-Up              resize-pane -U
bind-key -r -T prefix       C-Down            resize-pane -D
bind-key -r -T prefix       C-Left            resize-pane -L
bind-key -r -T prefix       C-Right           resize-pane -R

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename on

# remember history across sessions
set -g history-file ~/.tmux_history

# toggle status bar
bind-key b set-option status

### PLUGINS

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

# List of plugins
set -g @tpm_plugins '
    tmux-plugins/tpm \
    tmux-plugins/tmux-sensible \
    tmux-plugins/tmux-resurrect \
    tmux-plugins/tmux-continuum \
    niksingh710/minimal-tmux-status \
    sainnhe/tmux-fzf \
    tmux-plugins/tmux-yank \
'    

# enhanced session history
set -g @continuum-restore 'on'

# Theme
set -g @minimal-tmux-bg "#00FBB0"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "${TMUX_PLUGIN_MANAGER_PATH}tpm/tpm"
